name: CI/CD Piepline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Backend Docker Image
        uses: docker build -f api/Dockerfile -t backend-image .
      - name: Build Frontend Docker Image
        uses: docker build -f frontend/Dockerfile -t frontend-image .
      - name: Success message
        run: echo "Docker images built successfully!"
